name: Hello World
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-zlib mingw-w64-x86_64-ninja
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          cmake -B build -GNinja -DCMAKE_CXX_COMPILER=g++ .
          cd build
          cmake --build .
          ./Zipper-test
